development:
  client_id: 'PAQomNOuXDaaE0JKTFOlh4zgZ'
  client_secret: 'F8X9VMLbYd9RoAepsCcBUnHjEDsez5QLZVT3A8jKHZ04H83r3x'

test:
  client_id: 'PAQomNOuXDaaE0JKTFOlh4zgZ'
  client_secret: 'F8X9VMLbYd9RoAepsCcBUnHjEDsez5QLZVT3A8jKHZ04H83r3x'
